INSERT INTO products (id, product_name, price, image_url, quantity, description, category_id) 
VALUES 
(1, 'Ammonium Nitrate', 10, '/assets/Images/fertilizers/ammoniumNitrate.jpg', 50, 'Product 1 description', 3),
(2, 'Inhibitor', 19, '/assets/Images/fertilizers/inhibitor.jpg', 100, 'Product 2 description', 3),
(3, 'Nitrogen', 15, '/assets/Images/fertilizers/nitrogen.jpg', 20, 'Product 3 description', 3),
(4, 'Peat', 14, '/assets/Images/fertilizers/peat.jpg', 30, 'Product 4 description', 3),
(5, 'Phoshporous', 8, '/assets/Images/fertilizers/phoshporous.jpg', 15, 'Product 5 description', 3),
(6, 'Potassium', 12, '/assets/Images/fertilizers/potassium.jpg', 25, 'Product 6 description', 3),
(7, 'Slow Release', 9, '/assets/Images/fertilizers/slow_release.jpg', 10, 'Product 7 description', 3),
(8, 'Urea', 17, '/assets/Images/fertilizers/urea.jpg', 35, 'Product 8 description', 3),
(9, 'Vermicompost', 6, '/assets/Images/fertilizers/vermicompost.jpg', 18, 'Product 9 description', 3),
(10, 'Hand Cultivator', 6, '/assets/Images/gardening_equipments/hand_cultivator.jpg', 112, 'Product 10 description', 7),
(11, 'Hand Rake', 4, '/assets/Images/gardening_equipments/hand_rake.jpg', 112, 'Product 11 description', 7),
(12, 'Pruner', 12, '/assets/Images/gardening_equipments/pruner.jpg', 102, 'Product 12 description', 7),
(13, 'Trowel', 6, '/assets/Images/gardening_equipments/trowel.jpg', 112, 'Product 13 description', 7),
(14, 'Weeder', 6, '/assets/Images/gardening_equipments/weeder.jpg', 11, 'Product 14 description', 7),
(15, 'Biodegradable Bag', 6, '/assets/Images/grow_bags/biodegradable_grow_bags.jpg', 110, 'Product 15 description', 4),
(16, 'Fabric Bag', 6, '/assets/Images/grow_bags/fabric_bag.jpg', 200, 'Product 16 description', 4),
(17, 'HDPE Bag', 6, '/assets/Images/grow_bags/HDPE_bags.jpeg', 402, 'Product 17 description', 4),
(18, 'Bone Meal Manure', 66, '/assets/Images/grow_bags/Bone_meal.jpg', 112, 'Product 18 description', 6),
(19, 'Goat Manure', 26, '/assets/Images/grow_bags/goat.jpg', 100, 'Product 19 description', 6),
(20, 'Oil Cake', 15, '/assets/Images/grow_bags/oil_cake.jpg', 50, 'Product 20 description', 6),
(21, 'Poultry', 18, '/assets/Images/grow_bags/poultry.jpg', 75, 'Product 21 description', 6),
(22, 'Bactericide', 20, '/assets/Images/grow_bags/bactericide.jpg', 112, 'Product 22 description', 2),
(23, 'Fungicide', 25, '/assets/Images/grow_bags/fungicide.jpg', 80, 'Product 23 description', 2),
(24, 'Herbicide', 16, '/assets/Images/grow_bags/herbicide.jpg', 80, 'Product 24 description', 2),
(25, 'Insecticide', 17, '/assets/Images/grow_bags/Insecticide.jpg', 80, 'Product 25 description', 2),
(26, 'Larvicide', 5, '/assets/Images/grow_bags/Larvicide.jpg', 80, 'Product 26 description', 2),
(27, 'Rodenticide', 8, '/assets/Images/grow_bags/rodenticide.jpg', 80, 'Product 27 description', 2),
(28, 'Basil', 7, '/assets/Images/plants/basil.jpg', 80, 'Product 28 description', 5),
(29, 'Beans', 7, '/assets/Images/plants/beans.jpg', 80, 'Product 29 description', 5),
(30, 'Blueberry', 11, '/assets/Images/plants/blueberry.jpg', 80, 'Product 30 description', 5),
(31, 'Cucumber', 13, '/assets/Images/plants/cucumber.jpg', 80, 'Product 31 description', 5),
(32, 'Kale', 32, '/assets/Images/plants/kale.jpg', 80, 'Product 32 description', 5),
(33, 'Lettuce', 35, '/assets/Images/plants/lettuce.jpg', 80, 'Product 33 description', 5),
(34, 'Mint', 18, '/assets/Images/plants/mint.jpg', 80, 'Product 34 description', 5),
(35, 'Pepper', 45, '/assets/Images/plants/pepper.jpg', 80, 'Product 35 description', 5),
(36, 'Strawberries', 74, '/assets/Images/plants/strawberries.jpg', 80, 'Product 36 description', 5),
(37, 'Tomato', 89, '/assets/Images/plants/tomato.jpg', 80, 'Product 37 description', 5),
(38, 'Almond', 94, '/assets/Images/seeds/almond.jpg', 80, 'Product 38 description', 1),
(39, 'Bajra', 77, '/assets/Images/seeds/bajra.jpg', 80, 'Product 39 description', 1),
(40, 'Cashew', 85, '/assets/Images/seeds/cashew.jpg', 80, 'Product 40 description', 1),
(41, 'Channa', 56, '/assets/Images/seeds/channa.jpg', 80, 'Product 41 description', 1),
(42, 'Chia', 66, '/assets/Images/seeds/chia.jpg', 80, 'Product 42 description', 1),
(43, 'Flaxseeds', 72, '/assets/Images/seeds/flaxseeds.jpg', 80, 'Product 43 description', 1),
(44, 'Gram Pea', 44, '/assets/Images/seeds/grampea.jpg', 80, 'Product 44 description', 1),
(45, 'Pumpkin', 38, '/assets/Images/seeds/pumpkin.jpg', 80, 'Product 45 description', 1),
(46, 'Rajma', 70, '/assets/Images/seeds/rajma.jpg', 80, 'Product 46 description', 1),
(47, 'Sesame', 85, '/assets/Images/seeds/sesame.jpg', 80, 'Product 45 description', 1);